export interface Word {
  word: string;
  clue: string;
}

export const SPANISH_WORDS: Word[] = [
  // 3 Letras
  { word: "SOL", clue: "Estrella luminosa centro de nuestro sistema planetario" },
  { word: "MAR", clue: "Masa de agua salada que cubre gran parte de la Tierra" },
  { word: "PAN", clue: "Alimento básico hecho de harina y agua" },
  { word: "LUZ", clue: "Agente físico que hace visibles los objetos" },
  { word: "DOS", clue: "Uno más uno" },
  { word: "RIO", clue: "Corriente natural de agua continua" },
  { word: "SAL", clue: "Condimento blanco y cristalino" },
  { word: "SUR", clue: "Punto cardinal opuesto al norte" },
  { word: "UNO", clue: "Primer número natural" },
  { word: "PEZ", clue: "Animal acuático vertebrado" },
  { word: "RED", clue: "Tejido de mallas" },
  { word: "ORO", clue: "Metal precioso amarillo" },
  { word: "UVA", clue: "Fruto de la vid" },
  { word: "TOS", clue: "Expulsión brusca de aire por la boca" },
  { word: "REY", clue: "Monarca o soberano" },
  { word: "LEY", clue: "Regla o norma establecida" },
  { word: "VOZ", clue: "Sonido producido por las cuerdas vocales" },
  { word: "PAZ", clue: "Situación sin guerra ni conflictos" },
  { word: "GAS", clue: "Estado de la materia fluido y expansible" },
  { word: "OJO", clue: "Órgano de la vista" },

  // 4 Letras
  { word: "GATO", clue: "Felino doméstico" },
  { word: "CASA", clue: "Edificio para habitar" },
  { word: "LUNA", clue: "Satélite natural de la Tierra" },
  { word: "AGUA", clue: "Líquido vital transparente" },
  { word: "AIRE", clue: "Mezcla gaseosa que respiramos" },
  { word: "MANO", clue: "Parte del cuerpo con cinco dedos" },
  { word: "BOCA", clue: "Abertura para ingerir alimentos" },
  { word: "PIEL", clue: "Capa externa del cuerpo" },
  { word: "ROJO", clue: "Color de la sangre" },
  { word: "AZUL", clue: "Color del cielo despejado" },
  { word: "MESA", clue: "Mueble con tablero y patas" },
  { word: "SILLA", clue: "Asiento con respaldo" },
  { word: "CAMA", clue: "Mueble para dormir" },
  { word: "PERA", clue: "Fruta de forma alargada" },
  { word: "LOBO", clue: "Cánido salvaje" },
  { word: "RANA", clue: "Anfibio que salta" },
  { word: "PATO", clue: "Ave acuática palmípeda" },
  { word: "TORO", clue: "Macho de la vaca" },
  { word: "VACA", clue: "Hembra del toro" },
  { word: "LEON", clue: "Felino conocido como el rey de la selva" },
  { word: "TREN", clue: "Transporte sobre rieles" },
  { word: "AUTO", clue: "Vehículo automóvil" },
  { word: "NAVE", clue: "Embarcación o vehículo espacial" },
  { word: "ARTE", clue: "Expresión creativa humana" },
  { word: "CINE", clue: "Arte de las películas" },
  { word: "FOTO", clue: "Imagen capturada por cámara" },
  { word: "ROPA", clue: "Prendas de vestir" },
  { word: "TELA", clue: "Tejido hecho con fibras" },
  { word: "LANA", clue: "Pelo de las ovejas" },
  { word: "SEDA", clue: "Tejido fino y brillante" },

  // 5 Letras
  { word: "PERRO", clue: "El mejor amigo del hombre" },
  { word: "FUEGO", clue: "Combustión que produce calor y luz" },
  { word: "ARBOL", clue: "Planta grande con tronco leñoso" },
  { word: "LIBRO", clue: "Conjunto de hojas escritas encuadernadas" },
  { word: "LAPIZ", clue: "Instrumento de escritura de grafito" },
  { word: "RELOJ", clue: "Instrumento para medir el tiempo" },
  { word: "PLAYA", clue: "Ribera del mar o río" },
  { word: "MONTE", clue: "Elevación natural del terreno" },
  { word: "CAMPO", clue: "Terreno fuera de la ciudad" },
  { word: "CIELO", clue: "Espacio sobre la Tierra" },
  { word: "NUBES", clue: "Masas de vapor de agua en el cielo" },
  { word: "LLAVE", clue: "Instrumento para abrir cerraduras" },
  { word: "COCHE", clue: "Automóvil" },
  { word: "BARCO", clue: "Embarcación grande" },
  { word: "AVION", clue: "Aeronave más pesada que el aire" },
  { word: "HOTEL", clue: "Establecimiento de hospedaje" },
  { word: "RADIO", clue: "Medio de comunicación sonoro" },
  { word: "PIANO", clue: "Instrumento musical de teclas" },
  { word: "VIOLIN", clue: "Instrumento musical de cuerda" },
  { word: "FLAUTA", clue: "Instrumento musical de viento" },
  { word: "VERDE", clue: "Color de la vegetación" },
  { word: "NEGRO", clue: "Color más oscuro" },
  { word: "BLANCO", clue: "Color de la nieve" },
  { word: "DULCE", clue: "Sabor del azúcar" },
  { word: "ACIDO", clue: "Sabor del limón" },
  { word: "SALUD", clue: "Estado de bienestar" },
  { word: "MENTE", clue: "Facultad intelectual" },
  { word: "SUEÑO", clue: "Acto de dormir" },
  { word: "VIAJE", clue: "Desplazamiento a otro lugar" },
  { word: "MUNDO", clue: "El planeta Tierra y todo lo que existe" },

  // 6 Letras
  { word: "TIERRA", clue: "Planeta habitado" },
  { word: "CIUDAD", clue: "Población grande y urbanizada" },
  { word: "PUEBLO", clue: "Población pequeña" },
  { word: "CAMINO", clue: "Vía para transitar" },
  { word: "BOSQUE", clue: "Gran extensión de árboles" },
  { word: "JARDIN", clue: "Terreno donde se cultivan plantas" },
  { word: "PLANTA", clue: "Ser orgánico que crece y vive" },
  { word: "ANIMAL", clue: "Ser vivo que se mueve" },
  { word: "COMIDA", clue: "Alimento que se ingiere" },
  { word: "BEBIDA", clue: "Líquido que se bebe" },
  { word: "MUSICA", clue: "Arte de los sonidos" },
  { word: "PINTURA", clue: "Arte de pintar" },
  { word: "TEATRO", clue: "Arte escénico" },
  { word: "POESIA", clue: "Expresión artística por medio de la palabra" },
  { word: "NOVELA", clue: "Obra literaria narrativa" },
  { word: "ESCUELA", clue: "Lugar de enseñanza" },
  { word: "AMIGOS", clue: "Personas con las que se tiene amistad" },
  { word: "FAMILIA", clue: "Grupo de personas emparentadas" },
  { word: "TIEMPO", clue: "Duración de los sucesos" },
  { word: "DINERO", clue: "Medio de cambio y pago" },
  { word: "TRABAJO", clue: "Actividad productiva" },
  { word: "MEDICO", clue: "Profesional de la medicina" },
  { word: "DOCTOR", clue: "Título académico o médico" },
  { word: "POLICIA", clue: "Cuerpo encargado del orden" },
  { word: "BOMBERO", clue: "Persona que apaga incendios" },
  { word: "CARTERO", clue: "Persona que reparte cartas" },
  { word: "COCINA", clue: "Lugar donde se prepara comida" },
  { word: "SOTANO", clue: "Parte subterránea de un edificio" },
  { word: "BALCON", clue: "Plataforma que sobresale de una fachada" },
  { word: "PUERTA", clue: "Abertura para entrar y salir" },

  // 7 Letras
  { word: "MONTAÑA", clue: "Gran elevación natural del terreno" },
  { word: "ESTRELLA", clue: "Cuerpo celeste que brilla con luz propia" },
  { word: "PLANETA", clue: "Cuerpo celeste que orbita una estrella" },
  { word: "GALAXIA", clue: "Conjunto enorme de estrellas" },
  { word: "UNIVERSO", clue: "Totalidad del espacio y tiempo" },
  { word: "OCEANOS", clue: "Grandes masas de agua salada" },
  { word: "DESIERTO", clue: "Terreno arenoso y seco" },
  { word: "JUNGLA", clue: "Selva densa y tropical" },
  { word: "VOLCANES", clue: "Aberturas en la tierra que expulsan lava" },
  { word: "HURACAN", clue: "Viento de fuerza extraordinaria" },
  { word: "TORNADO", clue: "Viento a modo de torbellino" },
  { word: "TORMENTA", clue: "Perturbación atmosférica violenta" },
  { word: "GRANIZO", clue: "Lluvia helada y sólida" },
  { word: "INVIERNO", clue: "Estación más fría del año" },
  { word: "VERANO", clue: "Estación más calurosa del año" },
  { word: "OTOÑO", clue: "Estación de la caída de las hojas" },
  { word: "PRIMAVERA", clue: "Estación del renacer de las flores" },
  { word: "DOMINGO", clue: "Séptimo día de la semana" },
  { word: "SABADO", clue: "Sexto día de la semana" },
  { word: "VIERNES", clue: "Quinto día de la semana" },
  { word: "JUEVES", clue: "Cuarto día de la semana" },
  { word: "MIERCOLES", clue: "Tercer día de la semana" },
  { word: "MARTES", clue: "Segundo día de la semana" },
  { word: "LUNES", clue: "Primer día de la semana" },
  { word: "ENERO", clue: "Primer mes del año" },
  { word: "FEBRERO", clue: "Segundo mes del año" },
  { word: "AGOSTO", clue: "Octavo mes del año" },
  { word: "OCTUBRE", clue: "Décimo mes del año" },
  { word: "MAESTRO", clue: "Persona que enseña" },
  { word: "ALUMNO", clue: "Persona que aprende" },

  // 8 Letras
  { word: "ELEFANTE", clue: "Mamífero terrestre más grande" },
  { word: "JIRAFA", clue: "Animal de cuello muy largo" },
  { word: "BALLENA", clue: "Mamífero marino gigante" },
  { word: "DELFIN", clue: "Mamífero marino inteligente" },
  { word: "TIBURON", clue: "Pez depredador marino" },
  { word: "PINGUINO", clue: "Ave marina que no vuela" },
  { word: "AGUILA", clue: "Ave rapaz de gran vista" },
  { word: "HALCON", clue: "Ave rapaz veloz" },
  { word: "CONDOR", clue: "Ave rapaz de los Andes" },
  { word: "AVESTRUZ", clue: "Ave corredora de gran tamaño" },
  { word: "CANGURO", clue: "Marsupial saltador de Australia" },
  { word: "GORILA", clue: "Primate de gran tamaño" },
  { word: "MONO", clue: "Primate de cola larga" },
  { word: "CABALLO", clue: "Animal equino usado para montar" },
  { word: "OVEJA", clue: "Animal que produce lana" },
  { word: "CERDO", clue: "Animal de granja rosado" },
  { word: "GALLINA", clue: "Ave de granja que pone huevos" },
  { word: "POLLO", clue: "Cría de la gallina" },
  { word: "PAVO", clue: "Ave comestible de gran tamaño" },
  { word: "PATO", clue: "Ave acuática de pico plano" },
  { word: "CISNE", clue: "Ave acuática de cuello largo y elegante" },
  { word: "LORO", clue: "Ave que puede imitar la voz humana" },
  { word: "BUHO", clue: "Ave nocturna de grandes ojos" },
  { word: "LECHUZA", clue: "Ave nocturna parecida al búho" },
  { word: "MURCIELAGO", clue: "Mamífero volador nocturno" },
  { word: "RATON", clue: "Pequeño roedor" },
  { word: "CONEJO", clue: "Mamífero de orejas largas" },
  { word: "ARDILLA", clue: "Roedor que vive en los árboles" },
  { word: "CASTOR", clue: "Roedor constructor de presas" },
  { word: "ZORRO", clue: "Cánido astuto de cola tupida" },

  // 9 Letras
  { word: "COCODRILO", clue: "Reptil grande de ríos y pantanos" },
  { word: "SERPIENTE", clue: "Reptil sin patas que se arrastra" },
  { word: "TORTUGA", clue: "Reptil con caparazón" },
  { word: "LAGARTO", clue: "Reptil de cuatro patas y cola" },
  { word: "IGUANA", clue: "Reptil herbívoro de zonas cálidas" },
  { word: "CAMALEON", clue: "Reptil que cambia de color" },
  { word: "DINOSAURIO", clue: "Reptil extinto de gran tamaño" },
  { word: "MAMUT", clue: "Elefante extinto peludo" },
  { word: "SABUESO", clue: "Perro con gran olfato" },
  { word: "LABRADOR", clue: "Raza de perro cobrador" },
  { word: "PASTOR", clue: "Persona que cuida ganado" },
  { word: "GRANJERO", clue: "Persona que trabaja en una granja" },
  { word: "PESCADOR", clue: "Persona que pesca" },
  { word: "CAZADOR", clue: "Persona que caza" },
  { word: "MINERO", clue: "Persona que trabaja en una mina" },
  { word: "OBRERO", clue: "Trabajador manual" },
  { word: "ALBAÑIL", clue: "Persona que construye casas" },
  { word: "CARPINTERO", clue: "Persona que trabaja la madera" },
  { word: "FONTANERO", clue: "Persona que arregla tuberías" },
  { word: "ELECTRICISTA", clue: "Persona que instala electricidad" },
  { word: "MECANICO", clue: "Persona que repara máquinas" },
  { word: "CONDUCTOR", clue: "Persona que maneja un vehículo" },
  { word: "PILOTO", clue: "Persona que maneja un avión" },
  { word: "CAPITAN", clue: "Persona que manda en un barco" },
  { word: "SOLDADO", clue: "Persona que sirve en el ejército" },
  { word: "GENERAL", clue: "Jefe superior del ejército" },
  { word: "PRESIDENTE", clue: "Jefe de Estado" },
  { word: "MINISTRO", clue: "Jefe de un departamento del gobierno" },
  { word: "ALCALDE", clue: "Jefe de un ayuntamiento" },
  { word: "JUEZ", clue: "Persona que juzga y sentencia" },

  // 10 Letras
  { word: "ASTRONAUTA", clue: "Persona que viaja al espacio" },
  { word: "ASTRONOMIA", clue: "Ciencia que estudia los astros" },
  { word: "BIOLOGIA", clue: "Ciencia que estudia la vida" },
  { word: "QUIMICA", clue: "Ciencia de la composición de la materia" },
  { word: "FISICA", clue: "Ciencia de la materia y la energía" },
  { word: "MATEMATICAS", clue: "Ciencia de los números" },
  { word: "GEOGRAFIA", clue: "Ciencia que describe la Tierra" },
  { word: "HISTORIA", clue: "Ciencia que estudia el pasado" },
  { word: "LITERATURA", clue: "Arte de la expresión escrita" },
  { word: "FILOSOFIA", clue: "Amor por la sabiduría" },
  { word: "PSICOLOGIA", clue: "Ciencia de la mente y conducta" },
  { word: "SOCIOLOGIA", clue: "Ciencia de la sociedad" },
  { word: "ECONOMIA", clue: "Ciencia de los recursos y riqueza" },
  { word: "POLITICA", clue: "Arte de gobernar" },
  { word: "DERECHO", clue: "Conjunto de leyes y normas" },
  { word: "MEDICINA", clue: "Ciencia de la salud y curación" },
  { word: "ARQUITECTURA", clue: "Arte de proyectar y construir edificios" },
  { word: "INGENIERIA", clue: "Aplicación de la ciencia y tecnología" },
  { word: "TECNOLOGIA", clue: "Conjunto de conocimientos técnicos" },
  { word: "INFORMATICA", clue: "Ciencia del tratamiento de la información" },
  { word: "ORDENADOR", clue: "Máquina electrónica de procesamiento" },
  { word: "TELEVISION", clue: "Sistema de transmisión de imágenes" },
  { word: "TELEFONO", clue: "Sistema de comunicación por voz" },
  { word: "INTERNET", clue: "Red informática mundial" },
  { word: "PERIODICO", clue: "Publicación diaria de noticias" },
  { word: "REVISTA", clue: "Publicación periódica ilustrada" },
  { word: "BIBLIOTECA", clue: "Lugar donde se guardan libros" },
  { word: "MUSEO", clue: "Lugar de exposición de objetos" },
  { word: "HOSPITAL", clue: "Lugar de asistencia médica" },
  { word: "AEROPUERTO", clue: "Lugar de despegue y aterrizaje de aviones" }
];
